'use strict';
const { spawn } = require('node:child_process');
const path = require('node:path');
const fs = require('node:fs');
const { randomUUID } = require('node:crypto');
const root = path.resolve(__dirname, '..');
const fixture = path.join(root, 'output', `native-smoke-${randomUUID()}`);
fs.mkdirSync(fixture, { recursive: true });
const env = { ...process.env, DISKHARBOR_SMOKE_DIR: fixture, XDG_DATA_HOME: path.join(fixture, 'xdg-data') };
delete env.ELECTRON_RUN_AS_NODE;
delete env.DISKHARBOR_DEV_URL;
const child = spawn(require('electron'), [path.join(root, 'tests', 'electron-smoke.cjs')], { cwd: root, env, stdio: 'inherit' });
child.on('error', error => { console.error(error); process.exitCode = 1; });
child.on('exit', code => { process.exitCode = code ?? 1; });
